type Emoji = [string, string]
type EmojiGroup = [string, Emoji[]]
type EmojiList = EmojiGroup[]

const emoji: EmojiList = [
  [
    'Fruit',
    [
      ['🍇', 'Grapes'],
      ['🍈', 'Melon'],
      ['🍉', 'Watermelon'],
      ['🍊', 'Tangerine'],
      ['🍋', 'Lemon'],
      ['🍌', 'Banana'],
      ['🍍', 'Pineapple'],
      ['🥭', 'Mango'],
      ['🍎', 'Red Apple'],
      ['🍏', 'Green Apple'],
      ['🍐', 'Pear'],
      ['🍑', 'Peach'],
      ['🍒', 'Cherries'],
      ['🍓', 'Strawberry'],
      ['🥝', 'Kiwi Fruit'],
      ['🍅', 'Tomato'],
      ['🥥', 'Coconut'],
      ['🥑', 'Avocado'],
      ['🍆', 'Eggplant'],
    ],
  ],
  [
    'Vegetable',
    [
      ['🥔', 'Potato'],
      ['🥕', 'Carrot'],
      ['🌽', 'Ear of Corn'],
      ['🌶', 'Hot Pepper'],
      ['🥒', 'Cucumber'],
      ['🥬', 'Leafy Green'],
      ['🥦', 'Broccoli'],
      ['🧄', 'Garlic'],
      ['🧅', 'Onion'],
      ['🍄', 'Mushroom'],
      ['🥜', 'Peanuts'],
      ['🌰', 'Chestnut'],
    ],
  ],
  [
    'Baking',
    [
      ['🍞', 'Bread'],
      ['🥐', 'Croissant'],
      ['🥖', 'Baguette Bread'],
      ['🥨', 'Pretzel'],
      ['🥯', 'Bagel'],
      ['🥞', 'Pancakes'],
      ['🧇', 'Waffle'],
    ],
  ],
  [
    'Animal',
    [
      ['🧀', 'Cheese Wedge'],
      ['🍖', 'Meat on Bone'],
      ['🍗', 'Poultry Leg'],
      ['🥩', 'Cut of Meat'],
      ['🥓', 'Bacon'],
    ],
  ],
  [
    'Food',
    [
      ['🍔', 'Hamburger'],
      ['🍟', 'French Fries'],
      ['🍕', 'Pizza'],
      ['🌭', 'Hot Dog'],
      ['🥪', 'Sandwich'],
      ['🌮', 'Taco'],
      ['🌯', 'Burrito'],
      ['🥙', 'Stuffed Flatbread'],
      ['🧆', 'Falafel'],
      ['🍳', 'Cooking'],
      ['🥘', 'Shallow Pan of Food'],
      ['🍲', 'Pot of Food'],
      ['🥣', 'Bowl with Spoon'],
      ['🥗', 'Green Salad'],
      ['🍿', 'Popcorn'],
      ['🧈', 'Butter'],
      ['🧂', 'Salt'],
      ['🥫', 'Canned Food'],
      ['🍱', 'Bento Box'],
      ['🍘', 'Rice Cracker'],
      ['🍙', 'Rice Ball'],
      ['🍚', 'Cooked Rice'],
      ['🍛', 'Curry Rice'],
      ['🍜', 'Steaming Bowl'],
      ['🍝', 'Spaghetti'],
      ['🍠', 'Roasted Sweet Potato'],
      ['🍢', 'Oden'],
      ['🍣', 'Sushi'],
      ['🍤', 'Fried Shrimp'],
      ['🍥', 'Fish Cake with Swirl'],
      ['🥮', 'Moon Cake'],
      ['🍡', 'Dango'],
      ['🥟', 'Dumpling'],
      ['🥠', 'Fortune Cookie'],
      ['🥡', 'Takeout Box'],
      ['🦪', 'Oyster'],
      ['🍦', 'Soft Ice Cream'],
      ['🍧', 'Shaved Ice'],
      ['🍨', 'Ice Cream'],
      ['🍩', 'Doughnut'],
      ['🍪', 'Cookie'],
      ['🎂', 'Birthday Cake'],
      ['🍰', 'Shortcake'],
      ['🧁', 'Cupcake'],
      ['🥧', 'Pie'],
      ['🍫', 'Chocolate Bar'],
      ['🍬', 'Candy'],
      ['🍭', 'Lollipop'],
      ['🍮', 'Custard'],
      ['🍯', 'Honey Pot'],
      ['🍼', 'Baby Bottle'],
      ['🥛', 'Glass of Milk'],
      ['☕', 'Hot Beverage'],
      ['🍵', 'Teacup Without Handle'],
      ['🍶', 'Sake'],
      ['🍾', 'Bottle with Popping Cork'],
      ['🍷', 'Wine Glass'],
      ['🍸', 'Cocktail Glass'],
      ['🍹', 'Tropical Drink'],
      ['🍺', 'Beer Mug'],
      ['🍻', 'Clinking Beer Mugs'],
      ['🥂', 'Clinking Glasses'],
      ['🥃', 'Tumbler Glass'],
      ['🥤', 'Cup with Straw'],
      ['🧃', 'Beverage Box'],
      ['🧉', 'Mate'],
      ['🧊', 'Ice'],
      ['🥢', 'Chopsticks'],
      ['🍽', 'Fork and Knife with Plate'],
      ['🍴', 'Fork and Knife'],
      ['🥄', 'Spoon'],
    ],
  ],
]

export default emoji
